SERVER = [
    port = 8082;
    host = 127.2.15.1;
    allowed_methods = GET, POST, DELETE;
    max_body_size = 111111;
    server_names = www.Webserv.com, www.Webserv.ma;
    error_pages = 500:www/html/500.html, 502:www/html/502.html, 404:www/html/404.html, 403:www/html/403.html;

    route = / : ROOT=www/html/view, DEFAULT_FILE=index.html, ALLOWED_METHODS=GET-POST-DELETE;
    route = /cgi : ROOT=www/html/cgi, DEFAULT_FILE=cgi.html, ALLOWED_METHODS=GET-POST-DELETE, UPLOAD_DIR=www/html/uploads, CGI_EXTENTION =.php - .sh - .py ;
    route = /auto-index : ROOT=www/html/auto-index, ALLOWED_METHODS=GET, DIR_LISTING=on;
    route = /old : ROOT=www/html/old, DEFAULT_FILE=index.html, ALLOWED_METHODS=GET-POST-DELETE, UPLOAD_DIR=www/html/rediOploads;
    route = /uploads : ROOT=www/html/view/, UPLOAD_DIR=www/html/uploads, DEFAULT_FILE=uploadTest.html, ALLOWED_METHODS=POST-DELETE-GET, REDIRECT=303-/old;
]
